### PR TITLE
adding spacing and titles for admin sections

### PR DESCRIPTION
**Pull request by KaraAJC**
for better readability, I changed p tags for sections on each "tab" to h2, and left HR tags for separation.
Also added padding to better center the text so it doesnt look as overwhelming

### CODE REVIEW

**Comment by PilgrimMemoirs** [comment]
Again, Please don't make styling changes. Titles should not be centered. We played with that and it looks  better on the left in this format. 

The issue was to change to change the spacing in the paragraphs. If you feel the titles should be centered, submit an issue. don't change it. Communication please.

**Comment by KaraAJC** [comment]
these changes are to the admin page which is not styled at all. 

titles are to the left, but the content has padding on each site so it doesnt sit at the edge of the page. 
**before edits**
BEFORE
_after edits_*
screen shot 2015-05-11 at 8 52 37 am

**Comment by PilgrimMemoirs** [comment]
Oh gosh. Sorry about that Kara! 

This looks really good though!

**Comment by wiliajc87** [comment]
Yeah, this looks good.

**Pull request merged**
