### PR TITLE
Adding ransack to admin page

### PR DESCRIPTION
**Pull request by wiliajc87**

### CODE REVIEW

**Comment by thewildpendulum** [comment]
@KaraAJC Please review

**Comment by KaraAJC** [comment]
I checked out the code, which looks good, gonna test it in localhost now

**Comment by KaraAJC** [comment]
The search is working, so now we need to get the search functionality to load the results while remaining in the related tab (right now it refreshes the page and moves you back to the first tab, so you have to navigate back to the tab you searched in to see the results. 

go go gadget ajax!?!

**Comment by thewildpendulum** [comment]
Before we try Ajax, we should look at the request the search makes. It's
possible that we can use that information to set a flag in the view about
which tab should be visible when the page loads.

**Pull request merged**
