### PR TITLE
Deleting waste

### PR DESCRIPTION
**Pull request by wiliajc87**
This is my attempt to get rid of some unnecessary stuff.

### CODE REVIEW

**Comment by themphill** [comment]
You can leave the comments. Their size is next to nothing, but they help when developing.

**Comment by wiliajc87** [comment]
All of the comments I deleted are generic stuff generated by Rails, not comments we wrote. I mean, I can leave it, but I'm not sure it's going to change things one way or another and it's already up. (By that I really mean I'm not near my computer right now.)

**Comment by thewildpendulum** [comment]
Oh word. Go ahead then.

**Comment by KaraAJC** [comment]
looks fine to me.

**Pull request merged**
